# KSHRD Basic Course Student Performance Analytics

## 00. Data Collection & Understanding

This notebook documents the collection and initial understanding of the
KSHRD Basic Course student performance dataset.

The dataset contains monthly student results from March to June 2026.
The purpose of this project is to apply descriptive analytics to identify
student performance patterns, monthly trends, class performance, subject
performance, attendance patterns, and student status.

### Import Libraries

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

### Define the Raw Data Path

In [2]:
RAW_DATA_PATH = Path("../data/raw/Basic Course Score.xlsx")

RAW_DATA_PATH.exists()

True

### Load the Workbook

In [3]:
excel_file = pd.ExcelFile(RAW_DATA_PATH)

excel_file.sheet_names

['March', 'April', 'May', 'June']

### Load Each Sheet

In [5]:
sheets = {}

for sheet in excel_file.sheet_names:
    sheets[sheet] = pd.read_excel(RAW_DATA_PATH, sheet_name=sheet)

sheets.keys()

dict_keys(['March', 'April', 'May', 'June'])

### Initial Dataset Overview

In [6]:
for month, df in sheets.items():
    print(f"{month}: {df.shape}")

March: (56, 17)
April: (55, 18)
May: (54, 17)
June: (53, 15)

### Inspect Each Sheet

In [7]:
for month, df in sheets.items():
    print(f"\n{'='*50}")
    print(f"{month}")
    print(f"{'='*50}")
    display(df.head())

==================================================
March
==================================================

,Rank,Name,Gender,Class,Java (35%),Web (25%),Korean (30%),Att (10%),Total (100%),Scho.,Korean Benefit,Lunch,PA,M.S,E.A,Total,Comment
0,1,CHHIM POJIM,MALE,PP,28.32,18.17,25.32,10.0,81.81,45,30,30,10,NaN,NaN,135.0,CL
1,2,TY DINE,MALE,PVH,26.82,17.51,27.27,10.0,81.60,45,30,30,10,NaN,20.0,115.0,NaN
2,3,DONG SIENGLY,MALE,PP,28.25,16.71,26.31,10.0,81.27,45,30,30,10,1.0,NaN,116.0,NaN
3,4,UN SOVANNARA,MALE,PP,25.75,16.39,26.17,10.0,78.31,40,30,30,10,NaN,NaN,110.0,NaN
4,5,SOEUN SOVANNARITH,MALE,PVH,25.55,16.25,25.80,10.0,77.60,40,30,30,10,NaN,NaN,110.0,NaN

==================================================
April
==================================================

,Rank,Name,Gender,Class,Java (35%),Web (25%),Korean (30%),Att (10%),Total (100%),Scho.,Korean Benefit,Lunch,PA,M.S,Coding Challenge,E.A,Total,Comment
0,1,DONG SIENGLY,MALE,PP,27.33,18.01,24.05,10.00,79.40,40,15,30,10,3,11.5,NaN,109.5,NaN
1,2,TY DINE,MALE,PVH,23.56,17.19,26.93,10.00,77.68,40,30,30,10,2,NaN,NaN,112.0,NaN
2,3,HEAV SEIΜΑ,MALE,PP,23.78,19.95,22.91,9.25,75.89,40,15,30,0,3,11.5,NaN,99.5,NaN
3,4,CHHIM POЛМ,MALE,PP,24.81,15.91,24.09,7.00,71.81,0,15,30,0,6,NaN,20.0,71.0,CL
4,5,ROERN CHAMREUN,MALE,SR,26.40,21.00,16.61,10.00,74.01,0,0,30,10,4,17.0,20.0,81.0,CL

==================================================
May
==================================================

,Rank,Name,Gender,Class,Project Topic,IT (60%),Korean (30%),Att (10%),Total (100%),Scho.,Korean Benefit,Lunch,PA,M.S,E.A,Total,Comment
0,1,DONG SIENGLY,MALE,PP,APILens,48.56,23.33,10.00,81.89,65,15,30,10,14,NaN,134.0,NaN
1,2,TY DINE,MALE,PVH,HRD Eventhub,49.28,25.21,10.00,84.49,65,30,30,10,10,NaN,145.0,NaN
2,3,CHHIM POJM,MALE,PP,Kasephal,51.11,22.59,10.00,83.70,65,15,30,10,18,20.0,158.0,NaN
3,4,TIP DALIN,FEMALE,PP,APILens,49.87,22.70,5.50,78.07,60,15,30,0,22,NaN,89.5,W
4,5,HEAV SEIMA,MALE,PP,APILens,49.81,21.34,9.25,80.40,65,15,30,0,30,NaN,140.0,NaN

==================================================
June
==================================================

,Rank,Name,Gender,Class,Project Topic,IT (90%),Att (10%),Total (100%),Scho.,Lunch,PA,M.S,E.A,Total,Comment
0,1,SOEUN SOVANNARITH,MALE,PVH,SnapPos,81.81,10.0,91.81,60,30,10,7,35.0,142,NaN
1,2,PHENG MENGHEAK,MALE,PVH,SnapPos,81.56,10.0,91.56,60,30,10,4,NaN,104,NaN
2,3,CHEAM NORAKPANHA,MALE,PVH,SnapPos,81.06,10.0,91.06,60,30,10,2,NaN,102,NaN
3,4,SOVANNOEUT SREYNEAT,FEMALE,PVH,SnapPos,80.31,10.0,90.31,60,30,10,2,NaN,102,NaN
4,5,KEO VUTHTHANA,MALE,SR,EduTrace,79.96,10.0,89.96,55,30,10,7,NaN,102,NaN

In [8]:
for month, df in sheets.items():
    print(f"\n{month}")
    print(df.columns.tolist())

March
['Rank', 'Name', 'Gender', 'Class', 'Java (35%)', 'Web (25%)', 'Korean (30%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Korean Benefit', 'Lunch', 'PA', 'M.S', 'E.A', 'Total', 'Comment']

April
['Rank', 'Name', 'Gender', 'Class', 'Java (35%)', 'Web (25%)', 'Korean (30%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Korean Benefit', 'Lunch', 'PA', 'M.S', 'Coding Challenge', 'E.A', 'Total', 'Comment']

May
['Rank', 'Name', 'Gender', 'Class', 'Project Topic', 'IT (60%)', 'Korean (30%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Korean Benefit', 'Lunch', 'PA', 'M.S', 'E.A', 'Total', 'Comment']

June
['Rank', 'Name', 'Gender', 'Class', 'Project Topic', 'IT (90%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Lunch', 'PA', 'M.S', 'E.A', 'Total', 'Comment']

### Data Collection Summary

In [ ]:
summary = []

for month, df in sheets.items():
    summary.append(
        {
            "Month": month,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing Values": df.isna().sum().sum(),
            "Duplicate Rows": df.duplicated().sum(),
        }
    )

collection_summary = pd.DataFrame(summary)

collection_summary