# KSHRD Basic Course Student Performance Analytics

## 00. Data Collection & Understanding

This notebook documents the collection and initial understanding of the
KSHRD Basic Course student performance dataset.

The dataset contains monthly student results from March to June 2026.
The purpose of this project is to apply descriptive analytics to identify
student performance patterns, monthly trends, class performance, subject
performance, attendance patterns, and student status.

### Import Libraries

In [38]:
import pandas as pd
import numpy as np
from pathlib import Path

### Define the Raw Data Path

In [39]:
RAW_DATA_PATH = Path("../data/raw/Basic Course Score.xlsx")

RAW_DATA_PATH.exists()

True

### Load the Workbook

In [40]:
excel_file = pd.ExcelFile(RAW_DATA_PATH)

excel_file.sheet_names

['March', 'April', 'May', 'June']

### Load Each Sheet

In [41]:
sheets = {}

for sheet in excel_file.sheet_names:
    sheets[sheet] = pd.read_excel(RAW_DATA_PATH, sheet_name=sheet)

sheets.keys()

dict_keys(['March', 'April', 'May', 'June'])

### Initial Dataset Overview

In [42]:
for month, df in sheets.items():
    print(f"{month}: {df.shape}")

March: (56, 17)
April: (55, 18)
May: (54, 17)
June: (53, 15)

### Inspect Each Sheet

In [43]:
for month, df in sheets.items():
    print(f"\n{'='*50}")
    print(f"{month}")
    print(f"{'='*50}")
    display(df.head())

==================================================
March
==================================================

,Rank,Name,Gender,Class,Java (35%),Web (25%),Korean (30%),Att (10%),Total (100%),Scho.,Korean Benefit,Lunch,PA,M.S,E.A,Total,Comment
0,1,CHHIM POJIM,MALE,PP,28.32,18.17,25.32,10.0,81.81,45,30,30,10,NaN,NaN,135.0,CL
1,2,TY DINE,MALE,PVH,26.82,17.51,27.27,10.0,81.60,45,30,30,10,NaN,20.0,115.0,NaN
2,3,DONG SIENGLY,MALE,PP,28.25,16.71,26.31,10.0,81.27,45,30,30,10,1.0,NaN,116.0,NaN
3,4,UN SOVANNARA,MALE,PP,25.75,16.39,26.17,10.0,78.31,40,30,30,10,NaN,NaN,110.0,NaN
4,5,SOEUN SOVANNARITH,MALE,PVH,25.55,16.25,25.80,10.0,77.60,40,30,30,10,NaN,NaN,110.0,NaN

==================================================
April
==================================================

,Rank,Name,Gender,Class,Java (35%),Web (25%),Korean (30%),Att (10%),Total (100%),Scho.,Korean Benefit,Lunch,PA,M.S,Coding Challenge,E.A,Total,Comment
0,1,DONG SIENGLY,MALE,PP,27.33,18.01,24.05,10.00,79.40,40,15,30,10,3,11.5,NaN,109.5,NaN
1,2,TY DINE,MALE,PVH,23.56,17.19,26.93,10.00,77.68,40,30,30,10,2,NaN,NaN,112.0,NaN
2,3,HEAV SEIΜΑ,MALE,PP,23.78,19.95,22.91,9.25,75.89,40,15,30,0,3,11.5,NaN,99.5,NaN
3,4,CHHIM POЛМ,MALE,PP,24.81,15.91,24.09,7.00,71.81,0,15,30,0,6,NaN,20.0,71.0,CL
4,5,ROERN CHAMREUN,MALE,SR,26.40,21.00,16.61,10.00,74.01,0,0,30,10,4,17.0,20.0,81.0,CL

==================================================
May
==================================================

,Rank,Name,Gender,Class,Project Topic,IT (60%),Korean (30%),Att (10%),Total (100%),Scho.,Korean Benefit,Lunch,PA,M.S,E.A,Total,Comment
0,1,DONG SIENGLY,MALE,PP,APILens,48.56,23.33,10.00,81.89,65,15,30,10,14,NaN,134.0,NaN
1,2,TY DINE,MALE,PVH,HRD Eventhub,49.28,25.21,10.00,84.49,65,30,30,10,10,NaN,145.0,NaN
2,3,CHHIM POJM,MALE,PP,Kasephal,51.11,22.59,10.00,83.70,65,15,30,10,18,20.0,158.0,NaN
3,4,TIP DALIN,FEMALE,PP,APILens,49.87,22.70,5.50,78.07,60,15,30,0,22,NaN,89.5,W
4,5,HEAV SEIMA,MALE,PP,APILens,49.81,21.34,9.25,80.40,65,15,30,0,30,NaN,140.0,NaN

==================================================
June
==================================================

,Rank,Name,Gender,Class,Project Topic,IT (90%),Att (10%),Total (100%),Scho.,Lunch,PA,M.S,E.A,Total,Comment
0,1,SOEUN SOVANNARITH,MALE,PVH,SnapPos,81.81,10.0,91.81,60,30,10,7,35.0,142,NaN
1,2,PHENG MENGHEAK,MALE,PVH,SnapPos,81.56,10.0,91.56,60,30,10,4,NaN,104,NaN
2,3,CHEAM NORAKPANHA,MALE,PVH,SnapPos,81.06,10.0,91.06,60,30,10,2,NaN,102,NaN
3,4,SOVANNOEUT SREYNEAT,FEMALE,PVH,SnapPos,80.31,10.0,90.31,60,30,10,2,NaN,102,NaN
4,5,KEO VUTHTHANA,MALE,SR,EduTrace,79.96,10.0,89.96,55,30,10,7,NaN,102,NaN

In [44]:
for month, df in sheets.items():
    print(f"\n{month}")
    print(df.columns.tolist())

March
['Rank', 'Name', 'Gender', 'Class', 'Java (35%)', 'Web (25%)', 'Korean (30%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Korean Benefit', 'Lunch', 'PA', 'M.S', 'E.A', 'Total', 'Comment']

April
['Rank', 'Name', 'Gender', 'Class', 'Java (35%)', 'Web (25%)', 'Korean (30%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Korean Benefit', 'Lunch', 'PA', 'M.S', 'Coding Challenge', 'E.A', 'Total', 'Comment']

May
['Rank', 'Name', 'Gender', 'Class', 'Project Topic', 'IT (60%)', 'Korean (30%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Korean Benefit', 'Lunch', 'PA', 'M.S', 'E.A', 'Total', 'Comment']

June
['Rank', 'Name', 'Gender', 'Class', 'Project Topic', 'IT (90%)', 'Att (10%)', 'Total (100%)', 'Scho.', 'Lunch', 'PA', 'M.S', 'E.A', 'Total', 'Comment']

## Data Source

The dataset was collected from the monthly student result reports of the
KSHRD Basic Course for March, April, May, and June 2026.

The original Excel workbook contains one worksheet for each reporting month.
The raw workbook is preserved in its original form under `data/raw/` and is
used as the source for subsequent data cleaning and preparation.

### Initial Dataset Summary

In [45]:
summary = []

for month, df in sheets.items():
    summary.append(
        {
            "Month": month,
            "Rows": df.shape[0],
            "Columns": df.shape[1],
            "Missing Values": df.isna().sum().sum(),
            "Duplicate Rows": df.duplicated().sum(),
        }
    )

collection_summary = pd.DataFrame(summary)

collection_summary

   Month  Rows  Columns  Missing Values  Duplicate Rows
0  March    56       17             148               0
1  April    55       18             103               0
2    May    54       17              83               0
3   June    53       15              99               0

### Missing Values by Column

This section identifies missing values in each monthly dataset. The purpose is to understand where missing data occurs before making any cleaning or imputation decisions.

In [47]:
for month, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(month)
    print('=' * 60)

    missing = df.isna().sum()
    missing = missing[missing > 0].sort_values(ascending=False)

    display(missing.to_frame("Missing Values"))

============================================================
March
============================================================

         Missing Values
E.A                  53
M.S                  52
Comment              43

============================================================
April
============================================================

                  Missing Values
E.A                           52
Coding Challenge              29
Comment                       22

============================================================
May
============================================================

         Missing Values
E.A                  51
Comment              32

============================================================
June
============================================================

         Missing Values
Comment              53
E.A                  46

### Duplicate Student Names

This section checks whether multiple records within the same month have the same student name. This is important because student names may later be used to track performance across different months.

In [48]:
for month, df in sheets.items():
    duplicates = df[df["Name"].duplicated(keep=False)].sort_values("Name")

    print(f"\n{month}: {len(duplicates)} rows with duplicated names")

    if not duplicates.empty:
        display(
            duplicates[["Rank", "Name", "Gender", "Class"]]
        )

March: 0 rows with duplicated names

April: 0 rows with duplicated names

May: 0 rows with duplicated names

June: 0 rows with duplicated names

### Student Status Distribution

The `Comment` column contains student status information:

- `CL` = Class Leader
- `W` = Warning
- `2W` = Two Warnings
- Blank = No recorded status

In [49]:
for month, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(month)
    print('=' * 60)

    display(
        df["Comment"]
        .fillna("No Status")
        .value_counts()
        .to_frame("Count")
    )

============================================================
March
============================================================

           Count
Comment
No Status     43
2W             6
W              4
CL             2
W, CL          1

============================================================
April
============================================================

           Count
Comment
No Status     22
W             22
2W             7
CL             3
Dropped        1

============================================================
May
============================================================

           Count
Comment
No Status     32
W             12
2W             9
Dropped        1

============================================================
June
============================================================

           Count
Comment
No Status     53

### Data Types

This section examines the data types of the variables in each monthly dataset. This helps identify columns that may require conversion during the data cleaning and preparation stage.

In [50]:
for month, df in sheets.items():
    print(f"\n{'=' * 60}")
    print(month)
    print('=' * 60)

    display(df.dtypes.to_frame("Data Type"))

============================================================
March
============================================================

               Data Type
Rank               int64
Name                 str
Gender               str
Class                str
Java (35%)       float64
Web (25%)        float64
Korean (30%)     float64
Att (10%)        float64
Total (100%)     float64
Scho.              int64
Korean Benefit     int64
Lunch              int64
PA                 int64
M.S              float64
E.A              float64
Total            float64
Comment              str

============================================================
April
============================================================

                 Data Type
Rank                 int64
Name                   str
Gender                 str
Class                  str
Java (35%)         float64
Web (25%)          float64
Korean (30%)       float64
Att (10%)          float64
Total (100%)       float64
Scho.                int64
Korean Benefit       int64
Lunch                int64
PA                   int64
M.S                  int64
Coding Challenge   float64
E.A                float64
Total              float64
Comment                str

============================================================
May
============================================================

               Data Type
Rank               int64
Name                 str
Gender               str
Class                str
Project Topic        str
IT (60%)         float64
Korean (30%)     float64
Att (10%)        float64
Total (100%)     float64
Scho.              int64
Korean Benefit     int64
Lunch              int64
PA                 int64
M.S                int64
E.A              float64
Total            float64
Comment              str

============================================================
June
============================================================

              Data Type
Rank              int64
Name                str
Gender              str
Class               str
Project Topic       str
IT (90%)        float64
Att (10%)       float64
Total (100%)    float64
Scho.             int64
Lunch             int64
PA                int64
M.S               int64
E.A             float64
Total             int64
Comment         float64

## Initial Observations

Based on the initial inspection:

1. The dataset contains monthly student performance records from March
   through June 2026.

2. Each monthly worksheet represents a separate reporting period.

3. The number of columns is not identical across all months.

4. Some academic fields differ between reporting periods.

5. The dataset contains student demographic, academic, attendance,
   financial/benefit, ranking, and status information.

6. Further data cleaning and standardization are required before the
   monthly datasets can be combined for descriptive analysis.