# 00 - Understanding the Data

**Project:** KSHRD Basic Course Student Performance Analytics

This notebook focuses on understanding the structure, quality, and characteristics of the dataset before any data preparation or analysis is performed.

## Notebook Outline

1. Business Understanding
2. Project Objectives
3. Dataset Overview
4. Import Libraries
5. Load Dataset
6. Inspect Worksheets
7. Explore Dataset Structure
8. Data Profiling
9. Key Takeaways

## Project Objectives

The objectives of this project are:

- Understand the dataset structure.
- Assess data quality.
- Prepare the dataset for analysis.
- Analyze student performance.
- Identify performance trends.
- Create an interactive dashboard.

## Dataset Overview

The dataset consists of four monthly student reports.

- March 2026
- April 2026
- May 2026
- June 2026

Each worksheet contains one month's student performance.

In [ ]:
# Import Libraries
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [4]:
# Load Dataset
FILE_PATH = "../data/raw/Basic Course Score.xlsx"

excel = pd.ExcelFile(FILE_PATH)

excel.sheet_names

['March', 'April', 'May', 'June']

In [6]:
# Inspect Worksheets
datasets = {}

for sheet in excel.sheet_names:
    datasets[sheet] = pd.read_excel(FILE_PATH, sheet_name=sheet)

for month, df in datasets.items():
    print("=" * 100)
    print(month)
    print("=" * 100)

    display(df.head())

====================================================================================================
March
====================================================================================================

   Rank               Name Gender Class  Java (35%)  Web (25%)  Korean (30%)  Att (10%)  Total (100%)  Scho.  Korean Benefit  Lunch  PA  M.S   E.A  Total Comment
0     1        CHHIM POJIM   MALE    PP       28.32      18.17         25.32       10.0         81.81     45              30     30  10  NaN   NaN  135.0      CL
1     2            TY DINE   MALE   PVH       26.82      17.51         27.27       10.0         81.60     45              30     30  10  NaN  20.0  115.0     NaN
2     3       DONG SIENGLY   MALE    PP       28.25      16.71         26.31       10.0         81.27     45              30     30  10  1.0   NaN  116.0     NaN
3     4       UN SOVANNARA   MALE    PP       25.75      16.39         26.17       10.0         78.31     40              30     30  10  NaN   NaN  110.0     NaN
4     5  SOEUN SOVANNARITH   MALE   PVH       25.55      16.25         25.80       10.0         77.60     40              30     30  10  NaN   NaN  110.0     NaN

====================================================================================================
April
====================================================================================================

   Rank            Name Gender Class  Java (35%)  Web (25%)  Korean (30%)  Att (10%)  Total (100%)  Scho.  Korean Benefit  Lunch  PA  M.S  Coding Challenge   E.A  Total Comment
0     1    DONG SIENGLY   MALE    PP       27.33      18.01         24.05      10.00         79.40     40              15     30  10    3              11.5   NaN  109.5     NaN
1     2         TY DINE   MALE   PVH       23.56      17.19         26.93      10.00         77.68     40              30     30  10    2               NaN   NaN  112.0     NaN
2     3      HEAV SEIΜΑ   MALE    PP       23.78      19.95         22.91       9.25         75.89     40              15     30   0    3              11.5   NaN   99.5     NaN
3     4      CHHIM POЛМ   MALE    PP       24.81      15.91         24.09       7.00         71.81      0              15     30   0    6               NaN  20.0   71.0      CL
4     5  ROERN CHAMREUN   MALE    SR       26.40      21.00         16.61      10.00         74.01      0               0     30  10    4              17.0  20.0   81.0      CL

====================================================================================================
May
====================================================================================================

   Rank          Name  Gender Class Project Topic  IT (60%)  Korean (30%)  Att (10%)  Total (100%)  Scho.  Korean Benefit  Lunch  PA  M.S   E.A  Total Comment
0     1  DONG SIENGLY    MALE    PP       APILens     48.56         23.33      10.00         81.89     65              15     30  10   14   NaN  134.0     NaN
1     2       TY DINE    MALE   PVH  HRD Eventhub     49.28         25.21      10.00         84.49     65              30     30  10   10   NaN  145.0     NaN
2     3    CHHIM POJM    MALE    PP      Kasephal     51.11         22.59      10.00         83.70     65              15     30  10   18  20.0  158.0     NaN
3     4     TIP DALIN  FEMALE    PP       APILens     49.87         22.70       5.50         78.07     60              15     30   0   22   NaN   89.5       W
4     5    HEAV SEIMA    MALE    PP       APILens     49.81         21.34       9.25         80.40     65              15     30   0   30   NaN  140.0     NaN

====================================================================================================
June
====================================================================================================

   Rank                 Name  Gender Class Project Topic  IT (90%)  Att (10%)  Total (100%)  Scho.  Lunch  PA  M.S   E.A  Total  Comment
0     1    SOEUN SOVANNARITH    MALE   PVH       SnapPos     81.81       10.0         91.81     60     30  10    7  35.0    142      NaN
1     2       PHENG MENGHEAK    MALE   PVH       SnapPos     81.56       10.0         91.56     60     30  10    4   NaN    104      NaN
2     3     CHEAM NORAKPANHA    MALE   PVH       SnapPos     81.06       10.0         91.06     60     30  10    2   NaN    102      NaN
3     4  SOVANNOEUT SREYNEAT  FEMALE   PVH       SnapPos     80.31       10.0         90.31     60     30  10    2   NaN    102      NaN
4     5        KEO VUTHTHANA    MALE    SR      EduTrace     79.96       10.0         89.96     55     30  10    7   NaN    102      NaN

In [8]:
# Explore Dataset Structure
for month, df in datasets.items():
    print("=" * 50)
    print(month)
    print("=" * 50)

    print(f"Shape: {df.shape}")

    print()

    df.info()

==================================================
March
==================================================
Shape: (56, 17)

<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            56 non-null     int64
 1   Name            56 non-null     str
 2   Gender          56 non-null     str
 3   Class           56 non-null     str
 4   Java (35%)      56 non-null     float64
 5   Web (25%)       56 non-null     float64
 6   Korean (30%)    56 non-null     float64
 7   Att (10%)       56 non-null     float64
 8   Total (100%)    56 non-null     float64
 9   Scho.           56 non-null     int64
 10  Korean Benefit  56 non-null     int64
 11  Lunch           56 non-null     int64
 12  PA              56 non-null     int64
 13  M.S             4 non-null      float64
 14  E.A             3 non-null      float64
 15  Total           56 non-null     float64
 16  Comment         13 non-null     str
dtypes: float64(8), int64(5), str(4)
memory usage: 7.6 KB
==================================================
April
==================================================
Shape: (55, 18)

<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              55 non-null     int64
 1   Name              55 non-null     str
 2   Gender            55 non-null     str
 3   Class             55 non-null     str
 4   Java (35%)        55 non-null     float64
 5   Web (25%)         55 non-null     float64
 6   Korean (30%)      55 non-null     float64
 7   Att (10%)         55 non-null     float64
 8   Total (100%)      55 non-null     float64
 9   Scho.             55 non-null     int64
 10  Korean Benefit    55 non-null     int64
 11  Lunch             55 non-null     int64
 12  PA                55 non-null     int64
 13  M.S               55 non-null     int64
 14  Coding Challenge  26 non-null     float64
 15  E.A               3 non-null      float64
 16  Total             55 non-null     float64
 17  Comment           33 non-null     str
dtypes: float64(8), int64(6), str(4)
memory usage: 7.9 KB
==================================================
May
==================================================
Shape: (54, 17)

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            54 non-null     int64
 1   Name            54 non-null     str
 2   Gender          54 non-null     str
 3   Class           54 non-null     str
 4   Project Topic   54 non-null     str
 5   IT (60%)        54 non-null     float64
 6   Korean (30%)    54 non-null     float64
 7   Att (10%)       54 non-null     float64
 8   Total (100%)    54 non-null     float64
 9   Scho.           54 non-null     int64
 10  Korean Benefit  54 non-null     int64
 11  Lunch           54 non-null     int64
 12  PA              54 non-null     int64
 13  M.S             54 non-null     int64
 14  E.A             3 non-null      float64
 15  Total           54 non-null     float64
 16  Comment         22 non-null     str
dtypes: float64(6), int64(6), str(5)
memory usage: 7.3 KB
==================================================
June
==================================================
Shape: (53, 15)

<class 'pandas.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           53 non-null     int64
 1   Name           53 non-null     str
 2   Gender         53 non-null     str
 3   Class          53 non-null     str
 4   Project Topic  53 non-null     str
 5   IT (90%)       53 non-null     float64
 6   Att (10%)      53 non-null     float64
 7   Total (100%)   53 non-null     float64
 8   Scho.          53 non-null     int64
 9   Lunch          53 non-null     int64
 10  PA             53 non-null     int64
 11  M.S            53 non-null     int64
 12  E.A            7 non-null      float64
 13  Total          53 non-null     int64
 14  Comment        0 non-null      float64
dtypes: float64(5), int64(6), str(4)
memory usage: 6.3 KB

In [20]:
# Missing Values
for month, df in datasets.items():
    print("=" * 25)
    print(month)
    print("=" * 25)

    display(df.isnull().sum())

=========================
March
=========================

Rank               0
Name               0
Gender             0
Class              0
Java (35%)         0
Web (25%)          0
Korean (30%)       0
Att (10%)          0
Total (100%)       0
Scho.              0
Korean Benefit     0
Lunch              0
PA                 0
M.S               52
E.A               53
Total              0
Comment           43
dtype: int64

=========================
April
=========================

Rank                 0
Name                 0
Gender               0
Class                0
Java (35%)           0
Web (25%)            0
Korean (30%)         0
Att (10%)            0
Total (100%)         0
Scho.                0
Korean Benefit       0
Lunch                0
PA                   0
M.S                  0
Coding Challenge    29
E.A                 52
Total                0
Comment             22
dtype: int64

=========================
May
=========================

Rank               0
Name               0
Gender             0
Class              0
Project Topic      0
IT (60%)           0
Korean (30%)       0
Att (10%)          0
Total (100%)       0
Scho.              0
Korean Benefit     0
Lunch              0
PA                 0
M.S                0
E.A               51
Total              0
Comment           32
dtype: int64

=========================
June
=========================

Rank              0
Name              0
Gender            0
Class             0
Project Topic     0
IT (90%)          0
Att (10%)         0
Total (100%)      0
Scho.             0
Lunch             0
PA                0
M.S               0
E.A              46
Total             0
Comment          53
dtype: int64

In [ ]:
# Duplicate Records
for month, df in datasets.items():
    print("=" * 25)
    print(month)
    print("=" * 25)

    print(df.duplicated().sum())

March
0
April
0
May
0
June
0

## Initial Findings

- The workbook contains four monthly reports.
- Each worksheet represents one month.
- The number of students decreases over time.
- The assessment structure changes between months.
- Most students are male.
- The Comment column contains mostly blank values.
- No duplicate records were detected.