# 00 - Understanding the Data

## KSHRD Basic Course Student Performance Analytics

- This notebook focuses on understanding the dataset before any cleaning or transformation is performed.

- The goal is to inspect the dataset structure, assess data quality, and identify potential issues that need to be addressed during the data preparation stage.

---

### Notebook Outline

1. Business Understanding
2. Project Objectives
3. Dataset Overview
4. Import Libraries
5. Load Dataset
6. Inspect Worksheets
7. Dataset Structure
8. Data Quality Assessment
9. Initial Findings
10. Business Questions

---

### Project Objectives

The objectives of this project are:

- Understand the dataset structure.
- Assess data quality.
- Prepare the dataset for analysis.
- Analyze student performance.
- Identify performance trends.
- Create an interactive dashboard.

---

### Dataset Overview

The dataset consists of four monthly student reports.

- March 2026
- April 2026
- May 2026
- June 2026

Each worksheet contains one month's student performance.

---

#### Import Libraries

The following libraries are used throughout this notebook.
- pandas
- numpy

In [12]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

#### Load Dataset

- The monthly student performance reports are stored in a single Excel workbook.
- This section loads the workbook and identities the available worksheets.
- Each worksheet represents one month of student performance data.

In [13]:
FILE_PATH = "../data/raw/Basic Course Score.xlsx"

excel = pd.ExcelFile(FILE_PATH)

excel.sheet_names

['March', 'April', 'May', 'June']

#### Inspect Worksheets

- Before performing any analysis, it is important to inspect the structure of each worksheet.
- Displaying the first few records allows us to verify that the data has been loaded correctly and provides an initial understanding of the available information.

In [ ]:
datasets = {}

for sheet in excel.sheet_names:
    datasets[sheet] = pd.read_excel(FILE_PATH, sheet_name=sheet)

for month, df in datasets.items():
    print("=" * 80)
    print(month)
    print("=" * 80)

    display(df.head(3))

================================================================================
March
================================================================================

   Rank          Name Gender Class  Java (35%)  Web (25%)  Korean (30%)  Att (10%)  Total (100%)  Scho.  Korean Benefit  Lunch  PA  M.S   E.A  Total Comment
0     1   CHHIM POJIM   MALE    PP       28.32      18.17         25.32       10.0         81.81     45              30     30  10  NaN   NaN  135.0      CL
1     2       TY DINE   MALE   PVH       26.82      17.51         27.27       10.0         81.60     45              30     30  10  NaN  20.0  115.0     NaN
2     3  DONG SIENGLY   MALE    PP       28.25      16.71         26.31       10.0         81.27     45              30     30  10  1.0   NaN  116.0     NaN

================================================================================
April
================================================================================

   Rank          Name Gender Class  Java (35%)  Web (25%)  Korean (30%)  Att (10%)  Total (100%)  Scho.  Korean Benefit  Lunch  PA  M.S  Coding Challenge  E.A  Total Comment
0     1  DONG SIENGLY   MALE    PP       27.33      18.01         24.05      10.00         79.40     40              15     30  10    3              11.5  NaN  109.5     NaN
1     2       TY DINE   MALE   PVH       23.56      17.19         26.93      10.00         77.68     40              30     30  10    2               NaN  NaN  112.0     NaN
2     3    HEAV SEIΜΑ   MALE    PP       23.78      19.95         22.91       9.25         75.89     40              15     30   0    3              11.5  NaN   99.5     NaN

================================================================================
May
================================================================================

   Rank          Name Gender Class Project Topic  IT (60%)  Korean (30%)  Att (10%)  Total (100%)  Scho.  Korean Benefit  Lunch  PA  M.S   E.A  Total Comment
0     1  DONG SIENGLY   MALE    PP       APILens     48.56         23.33       10.0         81.89     65              15     30  10   14   NaN  134.0     NaN
1     2       TY DINE   MALE   PVH  HRD Eventhub     49.28         25.21       10.0         84.49     65              30     30  10   10   NaN  145.0     NaN
2     3    CHHIM POJM   MALE    PP      Kasephal     51.11         22.59       10.0         83.70     65              15     30  10   18  20.0  158.0     NaN

================================================================================
June
================================================================================

   Rank               Name Gender Class Project Topic  IT (90%)  Att (10%)  Total (100%)  Scho.  Lunch  PA  M.S   E.A  Total  Comment
0     1  SOEUN SOVANNARITH   MALE   PVH       SnapPos     81.81       10.0         91.81     60     30  10    7  35.0    142      NaN
1     2     PHENG MENGHEAK   MALE   PVH       SnapPos     81.56       10.0         91.56     60     30  10    4   NaN    104      NaN
2     3   CHEAM NORAKPANHA   MALE   PVH       SnapPos     81.06       10.0         91.06     60     30  10    2   NaN    102      NaN

#### Dataset Structure

- Understanding the structure of the dataset helps identify the number of observations, available attributes, and potential differences between monthly reports.

- This section summarizes the number of rows, columns, missing values, and duplicate records for each worksheet.

In [ ]:
summary = []

for month, df in datasets.items():
    summary.append({
        "Month": month,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Missing Values": df.isna().sum().sum(),
        "Duplicate Rows": df.duplicated().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

   Month  Rows  Columns  Missing Values  Duplicate Rows
0  March    56       17             148               0
1  April    55       18             103               0
2    May    54       17              83               0
3   June    53       15              99               0

#### Data Types

- Each column has an associated data type that determines how it should be processed.
- Verifying data types at an early stage helps identify potential issues such as numeric values stored as text or incorrectly formatted columns.-

In [16]:
for month, df in datasets.items():
    print(f"\n===== {month} =====")

    df.info()

===== March =====
<class 'pandas.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            56 non-null     int64
 1   Name            56 non-null     str
 2   Gender          56 non-null     str
 3   Class           56 non-null     str
 4   Java (35%)      56 non-null     float64
 5   Web (25%)       56 non-null     float64
 6   Korean (30%)    56 non-null     float64
 7   Att (10%)       56 non-null     float64
 8   Total (100%)    56 non-null     float64
 9   Scho.           56 non-null     int64
 10  Korean Benefit  56 non-null     int64
 11  Lunch           56 non-null     int64
 12  PA              56 non-null     int64
 13  M.S             4 non-null      float64
 14  E.A             3 non-null      float64
 15  Total           56 non-null     float64
 16  Comment         13 non-null     str
dtypes: float64(8), int64(5), str(4)
memory usage: 7.6 KB

===== April =====
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              55 non-null     int64
 1   Name              55 non-null     str
 2   Gender            55 non-null     str
 3   Class             55 non-null     str
 4   Java (35%)        55 non-null     float64
 5   Web (25%)         55 non-null     float64
 6   Korean (30%)      55 non-null     float64
 7   Att (10%)         55 non-null     float64
 8   Total (100%)      55 non-null     float64
 9   Scho.             55 non-null     int64
 10  Korean Benefit    55 non-null     int64
 11  Lunch             55 non-null     int64
 12  PA                55 non-null     int64
 13  M.S               55 non-null     int64
 14  Coding Challenge  26 non-null     float64
 15  E.A               3 non-null      float64
 16  Total             55 non-null     float64
 17  Comment           33 non-null     str
dtypes: float64(8), int64(6), str(4)
memory usage: 7.9 KB

===== May =====
<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Rank            54 non-null     int64
 1   Name            54 non-null     str
 2   Gender          54 non-null     str
 3   Class           54 non-null     str
 4   Project Topic   54 non-null     str
 5   IT (60%)        54 non-null     float64
 6   Korean (30%)    54 non-null     float64
 7   Att (10%)       54 non-null     float64
 8   Total (100%)    54 non-null     float64
 9   Scho.           54 non-null     int64
 10  Korean Benefit  54 non-null     int64
 11  Lunch           54 non-null     int64
 12  PA              54 non-null     int64
 13  M.S             54 non-null     int64
 14  E.A             3 non-null      float64
 15  Total           54 non-null     float64
 16  Comment         22 non-null     str
dtypes: float64(6), int64(6), str(5)
memory usage: 7.3 KB

===== June =====
<class 'pandas.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Rank           53 non-null     int64
 1   Name           53 non-null     str
 2   Gender         53 non-null     str
 3   Class          53 non-null     str
 4   Project Topic  53 non-null     str
 5   IT (90%)       53 non-null     float64
 6   Att (10%)      53 non-null     float64
 7   Total (100%)   53 non-null     float64
 8   Scho.          53 non-null     int64
 9   Lunch          53 non-null     int64
 10  PA             53 non-null     int64
 11  M.S            53 non-null     int64
 12  E.A            7 non-null      float64
 13  Total          53 non-null     int64
 14  Comment        0 non-null      float64
dtypes: float64(5), int64(6), str(4)
memory usage: 6.3 KB

#### Missing Values

- Missing values are common in real-world datasets.
- This section identifies columns containing missing values so that appropriate cleaning strategies can be determined during the data preparation stage.

In [ ]:
for month, df in datasets.items():
    print("=" * 25)
    print(month)
    print("=" * 25)

    display(df.isnull().sum())

=========================
March
=========================

Rank               0
Name               0
Gender             0
Class              0
Java (35%)         0
Web (25%)          0
Korean (30%)       0
Att (10%)          0
Total (100%)       0
Scho.              0
Korean Benefit     0
Lunch              0
PA                 0
M.S               52
E.A               53
Total              0
Comment           43
dtype: int64

=========================
April
=========================

Rank                 0
Name                 0
Gender               0
Class                0
Java (35%)           0
Web (25%)            0
Korean (30%)         0
Att (10%)            0
Total (100%)         0
Scho.                0
Korean Benefit       0
Lunch                0
PA                   0
M.S                  0
Coding Challenge    29
E.A                 52
Total                0
Comment             22
dtype: int64

=========================
May
=========================

Rank               0
Name               0
Gender             0
Class              0
Project Topic      0
IT (60%)           0
Korean (30%)       0
Att (10%)          0
Total (100%)       0
Scho.              0
Korean Benefit     0
Lunch              0
PA                 0
M.S                0
E.A               51
Total              0
Comment           32
dtype: int64

=========================
June
=========================

Rank              0
Name              0
Gender            0
Class             0
Project Topic     0
IT (90%)          0
Att (10%)         0
Total (100%)      0
Scho.             0
Lunch             0
PA                0
M.S               0
E.A              46
Total             0
Comment          53
dtype: int64

#### Duplicate Records

- Duplicate records may introduce bias into the analysis.
- This section checks whether any duplicate rows exist within each monthly report.

In [ ]:
for month, df in datasets.items():
    print("=" * 25)
    print(month)
    print("=" * 25)

    print(df.duplicated().sum())

=========================
March
=========================
0
=========================
April
=========================
0
=========================
May
=========================
0
=========================
June
=========================
0

#### Summary Statistics

- Descriptive statistics provide a quick overview of the numerical variables in the dataset.
- Key measures such as the mean, standard deviation, minimum, and maximum values help us understand the distribution of student scores.

In [ ]:
for month, df in datasets.items():
    display(df.describe())

            Rank  Java (35%)  Web (25%)  Korean (30%)  Att (10%)  Total (100%)      Scho.  Korean Benefit  Lunch         PA  M.S   E.A       Total
count  56.000000   56.000000  56.000000     56.000000  56.000000     56.000000  56.000000       56.000000   56.0  56.000000  4.0   3.0   56.000000
mean   28.500000   22.266071  14.419286     21.855357   9.112500     67.652679   8.125000       15.357143   30.0   5.535714  1.0  20.0   58.151786
std    16.309506    3.380033   2.634016      3.613057   1.584219      7.860199  16.612222       10.481895    0.0   5.016207  0.0   0.0   27.736245
min     1.000000   14.390000   5.390000     12.620000   1.500000     45.870000   0.000000        0.000000   30.0   0.000000  1.0  20.0   30.000000
25%    14.750000   20.380000  13.035000     19.377500   9.000000     63.020000   0.000000       10.000000   30.0   0.000000  1.0  20.0   40.000000
50%    28.500000   22.255000  14.360000     22.955000  10.000000     67.835000   0.000000       15.000000   30.0  10.000000  1.0  20.0   50.000000
75%    42.250000   24.855000  16.405000     25.185000  10.000000     72.492500   0.000000       30.000000   30.0  10.000000  1.0  20.0   62.500000
max    56.000000   28.320000  18.640000     27.270000  10.000000     81.810000  45.000000       30.000000   30.0  10.000000  1.0  20.0  135.000000

           Rank  Java (35%)  Web (25%)  Korean (30%)  Att (10%)  Total (100%)      Scho.  Korean Benefit  Lunch         PA        M.S  Coding Challenge   E.A       Total
count  55.00000   55.000000  55.000000     55.000000  55.000000     55.000000  55.000000       55.000000   55.0  55.000000  55.000000         26.000000   3.0   55.000000
mean   28.00000   18.902909  12.021636     19.231818   9.079091     59.234545   2.181818        8.909091   30.0   5.272727   2.672727         17.557692  20.0   55.245455
std    16.02082    3.906713   4.057772      4.245761   1.314509      9.830764   9.167355        8.260286    0.0   5.038572   1.656128          5.571942   0.0   17.757073
min     1.00000   11.450000   4.540000      9.730000   5.000000     36.650000   0.000000        0.000000   30.0   0.000000   0.000000         11.500000  20.0   32.000000
25%    14.50000   16.010000   8.860000     16.045000   8.750000     52.625000   0.000000        0.000000   30.0   0.000000   2.000000         11.500000  20.0   43.500000
50%    28.00000   18.290000  11.960000     20.590000  10.000000     59.690000   0.000000       15.000000   30.0  10.000000   2.000000         17.000000  20.0   52.000000
75%    41.50000   21.425000  14.850000     22.830000  10.000000     65.810000   0.000000       15.000000   30.0  10.000000   4.000000         25.000000  20.0   62.000000
max    55.00000   27.330000  21.000000     26.930000  10.000000     79.400000  40.000000       30.000000   30.0  10.000000   6.000000         25.000000  20.0  112.000000

            Rank   IT (60%)  Korean (30%)  Att (10%)  Total (100%)      Scho.  Korean Benefit  Lunch         PA        M.S   E.A       Total
count  54.000000  54.000000     54.000000  54.000000     54.000000  54.000000       54.000000   54.0  54.000000  54.000000   3.0   54.000000
mean   27.500000  50.056852     16.813148   9.121296     75.991296  35.462963        5.648148   30.0   4.444444  15.000000  20.0   86.620370
std    15.732133   1.884518      4.197465   1.337860      4.590924  30.887326        7.400044    0.0   5.015699   6.920028   0.0   37.599545
min     1.000000  46.780000      8.130000   5.000000     65.700000   0.000000        0.000000   30.0   0.000000   0.000000  20.0   30.000000
25%    14.250000  48.730000     13.530000   9.000000     72.880000   0.000000        0.000000   30.0   0.000000  10.000000  20.0   49.000000
50%    27.500000  49.645000     17.440000   9.500000     77.070000  60.000000        0.000000   30.0   0.000000  16.000000  20.0   87.750000
75%    40.750000  51.147500     20.000000  10.000000     79.497500  60.000000       13.750000   30.0  10.000000  19.000000  20.0  122.000000
max    54.000000  54.560000     25.210000  10.000000     84.490000  65.000000       30.000000   30.0  10.000000  30.000000  20.0  158.000000

            Rank   IT (90%)  Att (10%)  Total (100%)      Scho.  Lunch         PA        M.S        E.A       Total  Comment
count  53.000000  53.000000  53.000000     53.000000  53.000000   53.0  53.000000  53.000000   7.000000   53.000000      0.0
mean   26.943396  77.927925   9.436792     87.364717  54.716981   30.0   5.849057   6.037736  25.571429   99.981132      NaN
std    15.488724   1.973714   0.819601      2.226338   2.281846    0.0   4.974536   3.339520   9.071147   12.320231      NaN
min     1.000000  74.320000   7.000000     82.320000  50.000000   30.0   0.000000   0.000000  14.000000   84.000000      NaN
25%    14.000000  76.150000   9.250000     85.730000  55.000000   30.0   0.000000   3.000000  20.000000   93.000000      NaN
50%    27.000000  78.400000  10.000000     87.700000  55.000000   30.0  10.000000   7.000000  20.000000  101.000000      NaN
75%    40.000000  79.100000  10.000000     88.830000  55.000000   30.0  10.000000   8.000000  35.000000  104.000000      NaN
max    53.000000  81.810000  10.000000     91.810000  60.000000   30.0  10.000000  12.000000  35.000000  142.000000      NaN

In [ ]:
categorical_columns = [
    "Gender",
    "Class",
    "Comment"
]

for month, df in datasets.items():
    print("=" * 25)
    print(month)
    print("=" * 25)

    for col in categorical_columns:

        print(f"\n{col}")

        print(df[col].value_counts(dropna=False))

=========================
March
=========================

Gender
Gender
MALE      40
FEMALE    16
Name: count, dtype: int64

Class
Class
PP     20
PVH    19
SR     17
Name: count, dtype: int64

Comment
Comment
NaN      43
2W        6
W         4
CL        2
W, CL     1
Name: count, dtype: int64
=========================
April
=========================

Gender
Gender
MALE      39
FEMALE    16
Name: count, dtype: int64

Class
Class
PP     19
PVH    19
SR     17
Name: count, dtype: int64

Comment
Comment
NaN        22
W          22
2W          7
CL          3
Dropped     1
Name: count, dtype: int64
=========================
May
=========================

Gender
Gender
MALE      38
FEMALE    16
Name: count, dtype: int64

Class
Class
PP     19
PVH    18
SR     17
Name: count, dtype: int64

Comment
Comment
NaN        32
W          12
2W          9
Dropped     1
Name: count, dtype: int64
=========================
June
=========================

Gender
Gender
MALE      37
FEMALE    16
Name: count, dtype: int64

Class
Class
PVH    18
PP     18
SR     17
Name: count, dtype: int64

Comment
Comment
NaN    53
Name: count, dtype: int64

## Key Findings

From the initial inspection, the following observations were made:

- The workbook contains four monthly worksheets.
- Each worksheet represents one month of student performance.
- The number of students changes slightly across months.
- The assessment structure is not identical across all months.
- Most missing values occur in the Comment column.
- No duplicate records were identified.

# Business Questions

The following questions will guide the remainder of the project:

1. How has student performance changed from March to June?

2. Which class performs the best?

3. Does attendance influence academic performance?

4. How do Class Leaders perform compared with other students?

5. Which students show the greatest improvement over time?

6. Which assessment components contribute most to the total score?